export default MapData = Object.freeze([
  { q: -5, r: 2, data: "HOME" },
  { q: -5, r: 3, data: "rs" },
  { q: -4, r: -1, data: "cn" },
  { q: -4, r: 0, data: "sp" },
  { q: -4, r: 1, data: "pa" },
  { q: -4, r: 2, data: "tc" },
  { q: -4, r: 3, data: "pt" },
  { q: -4, r: 4, data: "vr" },
  { q: -3, r: -2, data: "HOME" },
  { q: -3, r: -1, data: "nr" },
  { q: -3, r: 0, data: "at", tunnel: true },
  { q: -3, r: 1, data: "nf" },
  { q: -3, r: 2, data: "cv" },
  { q: -3, r: 3, data: "rf", tunnel: true },
  { q: -3, r: 4, data: "fp" },
  { q: -2, r: -2, data: "vs" },
  { q: -2, r: -1, data: "fc" },
  { q: -2, r: 0, data: "vn" },
  { q: -2, r: 1, data: "sa" },
  { q: -2, r: 2, data: "ts" },
  { q: -2, r: 3, data: "sv" },
  { q: -2, r: 4, data: "HOME" },
]);
